name: test

on:
  push:
    branches:
    - main
    - fix-CI
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**.md'

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      # Test runs on Windows runners fail because tzdata package is missing.
      # However, they pass in an empty virtual environment on my machine,
      # where tzdata is not installed.
      shell: bash
      run: |
        pip install --upgrade pip &&
        pip install -r requirements-dev.txt &&
        if [ "$RUNNER_OS" == "Windows" ]; then
          pip install tzdata
        fi
    - name: Check formatting
      run: |
        black --check betfairdatabase tests &&
        isort --check betfairdatabase tests
    - name: Run tests
      run: |
        coverage run &&
        coverage report
    - name: Upload coverage to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: coveralls --service=github
